In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('usedCar_Dataset_0206.csv')

-----------------------------------------------------

In [3]:
data.shape

(2375350, 30)

In [4]:
data.columns

Index(['CarID', 'MakeId', 'Title', 'Year', 'Make', 'Model', 'Trim',
       'BodyStyle', 'Rental', 'Location', 'GasMileage_city',
       'GasMileage_highway', 'Price', 'Mileage', 'Transmission', 'FuelType',
       'ExteriorColor', 'InteriorColor', 'DoorsNum', 'MaximumSeating',
       'Engine', 'Drivetrain', 'VIN', 'OptionCount', 'MajorOptions',
       'Certified', 'Accident Check', 'OwnershipHistory', 'SellingDays',
       'OriginPrice'],
      dtype='object')

In [6]:
data.head(5)

CarID MakeId                                              Title  Year  \
0  100351603     m1                     2007 Chevrolet Tahoe - $11,999  2007   
1  101113873     m1                   2005 Chevrolet Express - $11,995  2005   
2  102996725     m1  2010 Chevrolet Silverado 2500HD Work Truck Ext...  2010   
3  103384798     m1  2014 Chevrolet Corvette Stingray 3LT Coupe RWD...  2014   
4  104800849     m1         2002 Chevrolet Monte Carlo SS FWD - $3,440  2002   

        Make             Model                            Trim     BodyStyle  \
0  Chevrolet             Tahoe                             NaN           suv   
1  Chevrolet           Express                             NaN           van   
2  Chevrolet  Silverado 2500HD  Work Truck Extended Cab LB 4WD  pickup_truck   
3  Chevrolet          Corvette          Stingray 3LT Coupe RWD         coupe   
4  Chevrolet       Monte Carlo                          SS FWD         coupe   

  Rental       Location  ... Engine         Drivetrain                VIN  \
0    NaN    Garland, TX  ...     V8                NaN  1GNFC13J47R120389   
1    NaN  Claremont, NH  ...    NaN                NaN  1GBJG31U251136588   
2    NaN  Frankfort, KY  ...     V8   Four-Wheel Drive  1GC5KVBG7AZ218246   
3    NaN  Lewistown, MT  ...     V8   Rear-Wheel Drive  1G1YE2D73E5104797   
4    NaN    Delavan, IL  ...     V6  Front-Wheel Drive  2G1WX15K829249749   

   OptionCount                                       MajorOptions Certified  \
0            0                                                NaN       NaN   
1            0                                                NaN       NaN   
2            2                           Steel Wheels,Tow Package       NaN   
3            5  Bluetooth,Backup Camera,Aluminum Wheels,Naviga...       NaN   
4            2                      Leather Seats,Aluminum Wheels       NaN   

  Accident Check OwnershipHistory SellingDays OriginPrice  
0            0.0              2.0        1873     12999.0  
1            1.0              1.0        1863         NaN  
2            0.0              2.0        1837     16900.0  
3            0.0              1.0        1832     62900.0  
4            0.0              2.0        1809      4800.0  

[5 rows x 30 columns]

In [9]:
data.groupby(by='MakeId').size().sort_values(ascending=False)

MakeId
m2      329590
m1      293079
m7      192976
m12     167186
m32     138695
m6      122921
m24     106549
m26      99698
m28      96737
m3       78226
m191     76643
m43      72802
m33      68444
m55      58642
m37      49712
m53      48757
m19      40281
m23      38940
m22      37894
m21      35364
m42      32988
m84      28800
m4       24941
m38      21555
m48      15158
m35      14283
m46      13522
m56      13177
m45      10680
m31       6989
m47       6474
m52       4682
m98       4135
m44       3307
m51       3205
m40       2774
m27       2110
m25       1870
m20       1596
m124      1249
m203      1146
m112      1144
m54        917
m50        872
m85        799
m34        691
m110       639
m49        629
m111       610
m141       483
m87        405
m30        249
m135        94
m194        40
m79          1
dtype: int64

---------------------------------------------------------------------------

In [61]:
car_m111 = data[data['MakeId'] == 'm111']

In [62]:
car_m111.shape

(610, 30)

In [63]:
car_m111 = car_m111.dropna(subset=['Price', 'Mileage', 'Accident Check', 'OwnershipHistory'])

In [64]:
car_m111.shape

(563, 30)

In [65]:
car_m111.dtypes

CarID                   int64
MakeId                 object
Title                  object
Year                    int64
Make                   object
Model                  object
Trim                   object
BodyStyle              object
Rental                 object
Location               object
GasMileage_city        object
GasMileage_highway     object
Price                 float64
Mileage               float64
Transmission           object
FuelType               object
ExteriorColor          object
InteriorColor          object
DoorsNum               object
MaximumSeating         object
Engine                 object
Drivetrain             object
VIN                    object
OptionCount             int64
MajorOptions           object
Certified              object
Accident Check        float64
OwnershipHistory      float64
SellingDays             int64
OriginPrice           float64
dtype: object

In [66]:
train_data = car_m111.iloc[:,[3,12,13,23,26,27,28,29]]

In [67]:
train_data.isnull().sum()

Year                  0
Price                 0
Mileage               0
OptionCount           0
Accident Check        0
OwnershipHistory      0
SellingDays           0
OriginPrice         318
dtype: int64

In [68]:
train_data.shape

(563, 8)

In [69]:
train_data = train_data.drop(columns=['OriginPrice'])

In [70]:
train_data.shape

(563, 7)

In [71]:
train_data.isnull().sum()

Year                0
Price               0
Mileage             0
OptionCount         0
Accident Check      0
OwnershipHistory    0
SellingDays         0
dtype: int64

In [72]:
train_data.head(5)

Year    Price  Mileage  OptionCount  Accident Check  OwnershipHistory  \
293718  2009   6999.0  46326.0            1             0.0               3.0   
293719  2009   6499.0  52273.0            1             0.0               3.0   
293720  2009   6499.0  50590.0            1             1.0               3.0   
293721  2009   6999.0  43284.0            1             0.0               3.0   
293722  2014  11950.0  62023.0            2             2.0               1.0   

        SellingDays  
293718         1395  
293719         1395  
293720         1395  
293721         1361  
293722          901

In [73]:
from sklearn.preprocessing import MinMaxScaler

In [74]:
mms = MinMaxScaler()

In [75]:
train_data.iloc[:,:] = mms.fit_transform(train_data.iloc[:,:])

In [77]:
train_data.head()

Year     Price   Mileage  OptionCount  Accident Check  \
293718   0.1  0.244936  0.223089          0.1             0.0   
293719   0.1  0.218901  0.251828          0.1             0.0   
293720   0.1  0.218901  0.243695          0.1             0.5   
293721   0.1  0.244936  0.208388          0.1             0.0   
293722   0.6  0.502734  0.298945          0.2             1.0   

        OwnershipHistory  SellingDays  
293718          0.333333     1.000000  
293719          0.333333     1.000000  
293720          0.333333     1.000000  
293721          0.333333     0.975627  
293722          0.000000     0.645878

In [80]:
train_data.shape

(563, 7)

----------------------------------------------------------------------------------------

In [81]:
from sklearn.cluster import DBSCAN

In [100]:
db = DBSCAN(eps=0.5,
    min_samples=30,
    metric='euclidean',
    n_jobs=None)

In [101]:
y_db = db.fit_predict(train_data)

In [102]:
np.unique(y_db)

array([-1,  0,  1], dtype=int64)

In [106]:
y_cluster = y_db[y_db >= 0]

In [107]:
np.bincount(y_cluster)

array([475,  71], dtype=int64)

------------------------------------------------------------------------------

In [108]:
car_m45 = data[data['MakeId'] == 'm45']
car_m45.shape

(10680, 30)

In [109]:
car_m45 = car_m45.dropna(subset=['Price', 'Mileage', 'Accident Check', 'OwnershipHistory'])
car_m45.shape

(9633, 30)

In [110]:
train_data2 = car_m45.iloc[:,[3,12,13,23,26,27,28,29]]

In [111]:
train_data2.isnull().sum()

Year                   0
Price                  0
Mileage                0
OptionCount            0
Accident Check         0
OwnershipHistory       0
SellingDays            0
OriginPrice         4160
dtype: int64

In [112]:
train_data2.shape

(9633, 8)

In [113]:
train_data2 = train_data2.drop(columns=['OriginPrice'])

In [114]:
train_data2.isnull().sum()

Year                0
Price               0
Mileage             0
OptionCount         0
Accident Check      0
OwnershipHistory    0
SellingDays         0
dtype: int64

In [115]:
train_data2.shape

(9633, 7)

In [128]:
train_data2.iloc[:,:] = mms.fit_transform(train_data2.iloc[:,:])

In [129]:
train_data2.head()

Year     Price   Mileage  OptionCount  Accident Check  \
1848599  0.444444  0.040342  0.433797         0.05             0.0   
1848600  0.277778  0.049399  0.249687         0.05             0.0   
1848601  0.333333  0.049423  0.115127         0.05             0.5   
1848602  0.000000  0.024699  0.604941         0.00             0.0   
1848604  0.055556  0.014820  0.444776         0.00             0.0   

         OwnershipHistory  SellingDays  
1848599               0.0     0.771326  
1848600               0.4     0.634658  
1848601               0.0     0.608307  
1848602               0.5     0.530147  
1848604               0.2     0.514962

In [130]:
train_data2.shape

(9633, 7)

In [156]:
db2 = DBSCAN(eps=0.1,
    min_samples=20,
    metric='euclidean',
    n_jobs=None)

In [157]:
%%time
y_db2 = db2.fit_predict(train_data2)

Wall time: 788 ms


In [158]:
np.unique(y_db2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7], dtype=int64)

In [159]:
y_cluster2 = y_db2[y_db2 >= 0]

In [160]:
np.bincount(y_cluster2)

array([4370, 1986,  317,  686,  237,  222,  109,   26], dtype=int64)